services:
  nextjs:
    image: vulhub/nextjs:15.2.2
    container_name: nextjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - webvulns

networks:
  webvulns:
    name: webvulns
    external: true
